package com.truc.interficie;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author Pep Lluís Simón Miquel, Antoni Aloy Torrens
 */
public class Credits extends javax.swing.JFrame {

    /**
     * Creates new form Credits
     */
    public Credits() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        license_url = new javax.swing.JLabel();
        license_text = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        license_url.setText("Llicència Pública General GNU, versió 3 o posterior.");
        license_url.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                license_urlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                license_urlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                license_urlMouseExited(evt);
            }
        });
        license_url.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                license_urlPropertyChange(evt);
            }
        });

        license_text.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                license_textPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(license_url, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(license_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(license_text, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(license_url, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void license_urlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_license_urlMouseClicked
        try {
            this.dispose();
            Desktop.getDesktop().browse(new URI("https://www.gnu.org/licenses/gpl-3.0.html"));
        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_license_urlMouseClicked

    private void license_urlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_license_urlMouseEntered
        license_url.setText("<html><a href='https://www.gnu.org/licenses/gpl-3.0.html'>Llicència Pública General GNU, versió 3 o posterior.</a></html>");
    }//GEN-LAST:event_license_urlMouseEntered

    private void license_urlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_license_urlMouseExited
        license_url.setText("Llicència Pública General GNU, versió 3 o posterior.");
    }//GEN-LAST:event_license_urlMouseExited

    private void license_urlPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_license_urlPropertyChange
        license_url.setForeground(Color.BLUE.darker());
        license_url.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_license_urlPropertyChange

    private void license_textPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_license_textPropertyChange
        license_text.setText("<html><body><p><b>TRUC</b></p><p>Realitzat per:</p><p><ul><li>Pep Lluís Simón Miquel</li><li>Antoni Aloy Torrens</li></ul></p><p>Aquest programa es proporciona sense cap tipus de garantia.</p><p>Per a més informació, visiteu:</p></body></html>");
    }//GEN-LAST:event_license_textPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel license_text;
    private javax.swing.JLabel license_url;
    // End of variables declaration//GEN-END:variables
}
